aplicacion/urls.py
from django.urls import path
from . import views
from .views import  CalleCreateView, CalleDeleteView, CalleListView, CalleUpdateView, ProfesionCreateView, ProfesionUpdateView, ProfesionDeleteView, ProfesionListView, NivelEducListView, NivelEducCreateView, NivelEducUpdateView, NivelEducDeleteView, BancoListView, BancoCreateView, BancoUpdateView, BancoDeleteView, CalleListView, CalleCreateView, CalleUpdateView, CalleDeleteView, register
from .views import obtener_informacion_jefe


urlpatterns = [
    path('', views.Bienvenido, name='Bienvenido'),
    path('ListaPersonas', views.ListaPersonas, name='ListaPersonas'),
    path('ListaPersonasEdicion', views.ListaPersonasEdicion, name='ListaPersonasEdicion'),
    path('agregar_persona/', views.agregar_persona, name='agregar_persona'),
    path('cargas_familiares/', views.lista_cargas_familiares, name='lista_cargas_familiares'),
    path('familias/detalle/<int:idfamilia>/', views.detalle_familia, name='detalle_familia'),
    path('ListaPagos', views.ListaPagos, name='ListaPagos'),
    path('actualizacion-de-datos/', views.actualizacion_de_datos, name='ruta_de_actualizacion_de_datos'),
    path('registrar_pagos/', views.registrar_pagos, name='registrar_pagos'),
    path('api/families_count', views.families_count, name='families_count'),
    path('api/residents_count', views.residents_count, name='residents_count'),
    path('api/payments_count', views.payments_count, name='payments_count'),
    path('informes/', views.informes, name='informes'),
    path('editar_persona/<int:persona_idPersona>/', views.editar_persona, name='editar_persona'),
    path('editar_persona_carga/<int:persona_idPersona>/', views.editar_persona_carga, name='editar_persona_carga'),
    path('eliminar_persona/<int:persona_idPersona>/', views.eliminar_persona, name='eliminar_persona'),
    path('detalle_persona/<int:persona_id>/', views.detalle_persona, name='detalle_persona'),
    path('eliminar_pago/<int:pago_id>/', views.eliminar_pago, name='eliminar_pago'),
    path('editar_pago/<int:pago_id>/', views.editar_pago, name='editar_pago'),
    path('eliminar_persona_carga/<int:persona_idPersona>/', views.eliminar_persona_carga, name='eliminar_persona_carga'),
    path('familias/detalle/<int:familia_id>/agregar_persona_carga/', views.agregar_persona_carga, name='agregar_persona_carga'),
    path('seleccionar_bloque/', views.seleccionar_bloque, name='seleccionar_bloque'),
    path('generar_pdf_jefes_familia/<str:selected_bloque>/', views.generar_pdf_jefes_familia, name='generar_pdf_jefes_familia'),
    path('reporte_pagos/', views.reporte_pagos, name='reporte_pagos'),
    path('profesion/', ProfesionListView.as_view(), name='profesion-list'),
    path('profesion/create/', ProfesionCreateView.as_view(), name='profesion-create'),
    path('profesion/update/<int:pk>/', ProfesionUpdateView.as_view(), name='profesion-update'),
    path('profesion/delete/<int:pk>/', ProfesionDeleteView.as_view(), name='profesion-delete'),
    path('nivel_educ/', NivelEducListView.as_view(), name='nivel-educ-list'),
    path('nivel_educ/create/', NivelEducCreateView.as_view(), name='nivel-educ-create'),
    path('nivel_educ/update/<int:pk>/', NivelEducUpdateView.as_view(), name='nivel-educ-update'),
    path('nivel_educ/delete/<int:pk>/', NivelEducDeleteView.as_view(), name='nivel-educ-delete'),
    path('banco/', BancoListView.as_view(), name='banco-list'),
    path('banco/create/', BancoCreateView.as_view(), name='banco-create'),
    path('banco/update/<int:pk>/', BancoUpdateView.as_view(), name='banco-update'),
    path('banco/delete/<int:pk>/', BancoDeleteView.as_view(), name='banco-delete'),
    path('bloque/', views.BloqueListView.as_view(), name='bloque-list'),
    path('bloque/create/', views.BloqueCreateView.as_view(), name='bloque-create'),
    path('bloque/update/<int:pk>/', views.BloqueUpdateView.as_view(), name='bloque-update'),
    path('bloque/delete/<int:pk>/', views.BloqueDeleteView.as_view(), name='bloque-delete'),
    path('calle/', CalleListView.as_view(), name='calle-list'),
    path('calle/create/', CalleCreateView.as_view(), name='calle-create'),
    path('calle/update/<int:pk>/', CalleUpdateView.as_view(), name='calle-update'),
    path('calle/delete/<int:pk>/', CalleDeleteView.as_view(), name='calle-delete'),
    path('salir',views.salir, name='salir'),
    path('register/', views.register, name ='register' ),
    path('permiso-denegado/', views.permiso_denegado, name='PermisoDenegado'),
    path('seleccionar_bloque_carga/', views.seleccionar_bloque_carga, name='seleccionar_bloque_carga'),
    path('generar_pdf_carga_familiar/<str:selected_bloque>/', views.generar_pdf_carga_familiar, name='generar_pdf_carga_familiar'),
    path('reporte_familias/', views.reporte_familias, name='reporte_familias'),
    path('registro/', views.registro , name='registro'),
    path('obtener_informacion_jefe/<int:familia_id>/', obtener_informacion_jefe, name='obtener_informacion_jefe'),
 



]



aplicacion/forms.py
from django import forms
from .models import Familia, Persona, Banco, Pagos, Bloque, Profesion, Nivel_Educ, Calle
from django.urls import reverse
from io import BytesIO
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from django.core.validators import MinLengthValidator, MaxLengthValidator
from django.shortcuts import get_object_or_404
from django.db.models import Count
from .choices import parentesco




class FamiliaForm(forms.ModelForm):
    class Meta:
        model = Familia
        fields = '__all__'




class PersonaForm(forms.ModelForm):
    familia_r = forms.ModelChoiceField(
        queryset=Familia.objects.filter(jefe_de_familia__isnull=False),  # Filtra las familias con jefe de familia
        required=False,
        widget=forms.Select(attrs={'class': 'select2'})
    )

    discapacidad = forms.BooleanField(
        required=False,
        widget=forms.RadioSelect(choices=((True, 'Sí'), (False, 'No'))),
        initial=False
    )
    
    descripcion_discapacidad = forms.CharField(
        required=False,
        widget=forms.Textarea(attrs={'style': 'display: none;'}),
        label='Descripción Discapacidad'
    )

    ocupacion = forms.BooleanField(
        required=False,
        widget=forms.RadioSelect(choices=((True, 'Sí'), (False, 'No'))),
        initial=False
    )
    
    descripcion_ocupacion = forms.CharField(
        required=False,
        widget=forms.Textarea(attrs={'style': 'display: none;'}),
        label='Descripción Ocupación'
    )
    
    SINO_CHOICES = (
        (True, 'Sí'),
        (False, 'No'),
    )
    
    trabaja = forms.ChoiceField(
        choices=SINO_CHOICES,
        widget=forms.RadioSelect,
        required=True,
        initial=False  # Cambiado a False
    )

    jefe_familia = forms.ChoiceField(
        choices=[(0, "No"), (1, "Sí")],
        initial=0,  # Establece "No" como valor predeterminado
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    carga_familiar = forms.ChoiceField(
        choices=[(0, "No"), (1, "Sí")],
        initial=0,  # Establece "No" como valor predeterminado
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    num_calle = forms.ModelChoiceField(
        queryset=Calle.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'}),
        required=True  # Este campo es obligatorio
    )

    num_bloque = forms.ModelChoiceField(
        queryset=Bloque.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'}),
        required=True  # Este campo es obligatorio
    )

    parentesco = forms.ChoiceField(
    choices=parentesco,  # Agrega esta línea
    widget=forms.Select(attrs={'class': 'form-control'}),
    required=False,
    )


    cedula = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control custom-input'}), required=False)

    def clean(self):
        cleaned_data = super().clean()
        carga_familiar = cleaned_data.get('carga_familiar')
        familia_r = cleaned_data.get('familia_r')
        parentesco = cleaned_data.get('parentesco')

        if carga_familiar == 1:
            if not familia_r:
                self.add_error('familia_r', 'Si es carga familiar, debes seleccionar una familia en "Familia"')
            if not parentesco:
                self.add_error('parentesco', 'Si es carga familiar, debes especificar un parentesco')


        print("Carga familiar:", carga_familiar)
        print("Familia:", familia_r)
        print("Parentesco:", parentesco)

        return cleaned_data
    
    
    class Meta:
        model = Persona
        fields = '__all__'
        widgets = {
            'fecha_nacimiento': forms.DateInput(attrs={'type': 'date'}),
            # Otros widgets para otros campos si es necesario
        }


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

                # Para el campo 'profesion'
        self.fields['profesion'].queryset = Profesion.objects.all()
        self.fields['profesion'].empty_label = None

        # Para el campo 'nivel_educativo'
        self.fields['nivel_educ'].queryset = Nivel_Educ.objects.all()
        self.fields['nivel_educ'].empty_label = None


        # Verificar si la instancia actual está editando una persona existente
        if self.instance.pk and self.instance.familia_r and self.instance.familia_r.jefe_de_familia:
            # Si está editando y la persona tiene una familia asociada, incluimos la familia actual de la persona
            familia_actual = self.instance.familia_r
            familias_con_menos_de_7 = Familia.objects.annotate(num_personas=Count('familia_personas')).filter(num_personas__lt=7) | Familia.objects.filter(idfamilia=familia_actual.idfamilia)
        else:
            # Si está creando una nueva persona o la persona no tiene una familia asociada, simplemente contamos todas las familias
            familias_con_menos_de_7 = Familia.objects.annotate(num_personas=Count('familia_personas')).filter(num_personas__lt=7)

        # Actualizar el queryset del campo familia_r
        self.fields['familia_r'].queryset = familias_con_menos_de_7





        

class PagosForm(forms.ModelForm):
    jefe_de_familia = forms.ModelChoiceField(
        queryset=Familia.objects.filter(jefe_de_familia__isnull=False),
        required=True,
        widget=forms.Select(attrs={'class': 'form-control select2 jefe-familia-select', 'style': 'height: 50px;'}),
    )

    banco_receptor = forms.ModelChoiceField(
        queryset=Banco.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control border-blue', 'style': 'height: 50px;'}),
        required=True
    )

    banco_emisor = forms.ModelChoiceField(
        queryset=Banco.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control border-blue', 'style': 'height: 50px;'}),
        required=True
    )

    numero_referencia = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control border-blue'}),
        required=True  # Este campo es obligatorio
    )

    def clean_numero_referencia(self):
        numero_referencia = self.cleaned_data['numero_referencia']
        if not numero_referencia.isdigit() or len(numero_referencia) != 6:
            raise forms.ValidationError("Solo se permiten números (6).")
        return numero_referencia

    monto = forms.DecimalField(
        widget=forms.NumberInput(attrs={'class': 'form-control border-blue'}),
        required=True  # Este campo es obligatorio
    )

    comprobante_pago = forms.FileField(
        required=False  # Este campo no es obligatorio
    )

    class Meta:
        model = Pagos
        fields = ['fecha', 'jefe_de_familia', 'banco_receptor', 'banco_emisor', 'numero_referencia', 'monto', 'comprobante_pago', 'observaciones']
        widgets = {
            'fecha': forms.DateInput(attrs={'type': 'date', 'class': 'form-control border-blue'}),
            # Otros widgets para otros campos si es necesario
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Puedes agregar más personalización si es necesario
        self.fields['fecha'].widget.attrs.update({'class': 'form-control border-blue'})  # Agrega clases al campo 'fecha'
        self.fields['numero_referencia'].widget.attrs.update({'class': 'form-control border-blue'})  # Agrega clases al campo 'numero_referencia'
        self.fields['monto'].widget.attrs.update({'class': 'form-control border-blue'})  # Agrega clases al campo 'monto'
        self.fields['comprobante_pago'].widget.attrs.update({'class': 'form-control border-blue'})  # Agrega clases al campo 'comprobante_pago'
        self.fields['observaciones'].widget.attrs.update({'class': 'form-control border-blue'})  # Agrega clases al campo 'observaciones'



class BancoForm(forms.ModelForm):
    class Meta:
        model = Banco
        fields = '__all__'


class ReportePagosForm(forms.Form):
    bloque_choices = [(bloque.id, str(bloque)) for bloque in Bloque.objects.all()]
    bloque_choices.append(('all', 'Todos los Bloques'))
    bloque = forms.ChoiceField(choices=bloque_choices, required=False, label="Bloque")
    mes_anio = forms.CharField(required=False, label="Mes y Año")


class ProfesionForm(forms.ModelForm):
    class Meta:
        model = Profesion
        fields = ['nombre_profesion']

    nombre_profesion = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control my-custom-input'})
    )


class NivelEducForm(forms.ModelForm):
    class Meta:
        model = Nivel_Educ
        fields = ['nombre_Nivel']

    nombre_Nivel = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control my-custom-input'})
    )

    def clean_nombre(self):
        nombre = self.cleaned_data['nombre_Nivel']
        if not nombre.isalpha():
            raise forms.ValidationError("Solo se permiten letras y espacios en blanco.")
        return nombre



class BloqueForm(forms.ModelForm):
    class Meta:
        model = Bloque
        fields = ['numero_bloque']
        widgets = {
            'numero_bloque': forms.TextInput(attrs={'class': 'form-control'}),
        }


class CalleForm(forms.ModelForm):
    class Meta:
        model = Calle
        fields = ['numero_calle']

class CustomUserCreationForm(UserCreationForm):
    group = forms.ModelChoiceField(queryset=Group.objects.all(), empty_label=None, label='Grupo')

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2', 'group']



class RegistroForm(forms.ModelForm):
    class Meta:

aplicacion/templates/banco_confirm_delete.html
{% extends "base.html" %}

{% block contenido %}
  <div class="card" style="max-width: 600px; margin: 0 auto;">
    <div class="card-header">
      <h2>¿Estás seguro de que deseas eliminar el bloque "{{ object }}"?</h2>
    </div>
    <div class="card-body">
      <form method="post">
        {% csrf_token %}
        <div class="mb-3">
          <p class="lead">Esta acción no se puede deshacer.</p>
        </div>
        <button type="submit" class="btn btn-danger">Eliminar</button>
        <a href="{% url 'banco-list' %}" class="btn btn-secondary ml-2">Cancelar</a>
      </form>
    </div>
  </div>
{% endblock %}


aplicacion/templates/banco_form.html
{% extends "base.html" %}

{% block contenido %}
  <div class="container mt-0">
    <div class="card text-center" style="max-width: 600px; margin: 0 auto;">
      <div class="card-header">
        <div class="titulo">
          <h2>Agregar Banco:</h2>
        </div>
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          <div class="mb-3">
            {{ form.codigo.label_tag }}
            <input type="text" name="codigo" class="form-control" value="{{ form.codigo.value|default:'' }}" oninput="validarNumeros(this)">
            <div class="error-message-codigo" style="color: red;"></div>
          </div>
          <div class="mb-3">
            {{ form.nombre.label_tag }}
            <input type="text" name="nombre" class="form-control" value="{{ form.nombre.value|default:'' }}" oninput="validarLetras(this)">
            <div class="error-message-nombre" style="color: red;"></div>
          </div>
          <button type="submit" class="btn btn-primary btn-block">Guardar</button>
        </form>
      </div>
      <div class="card-footer">
        <a href="{% url 'banco-list' %}" class="btn btn-secondary btn-block mt-2">Volver a la lista de Bancos</a>
      </div>
    </div>
  </div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        function validarNumeros(inputField) {
            const valor = inputField.value;
            const contieneLetras = /[a-zA-Z]/.test(valor);

            if (contieneLetras) {
                inputField.value = valor.replace(/[a-zA-Z]/g, ''); // Elimina las letras del valor
                // Muestra un mensaje de error
                document.querySelector(".error-message-codigo").textContent = "Este campo debe contener solo números.";
            } else {
                // Borra el mensaje de error si es válido
                document.querySelector(".error-message-codigo").textContent = "";
            }
        }

        function validarLetras(inputField) {
            const valor = inputField.value;
            const contieneNumeros = /\d/.test(valor);

            if (contieneNumeros) {
                inputField.value = valor.replace(/\d/g, ''); // Elimina los números del valor
                // Muestra un mensaje de error
                document.querySelector(".error-message-nombre").textContent = "Este campo debe contener solo letras.";
            } else {
                // Borra el mensaje de error si es válido
                document.querySelector(".error-message-nombre").textContent = "";
            }
        }

        const camposDeTexto = document.querySelectorAll('input[type="text"], textarea');
        camposDeTexto.forEach(function (campo) {
            if (campo.name === 'codigo') {
                campo.addEventListener("input", function () {
                    validarNumeros(campo);
                });
            } else if (campo.name === 'nombre') {
                campo.addEventListener("input", function () {
                    validarLetras(campo);
                });
            }
        });
    });

    document.addEventListener("DOMContentLoaded", function () {
      // Función para convertir texto a mayúsculas
      function convertirAMayusculas(inputField) {
          inputField.value = inputField.value.toUpperCase();
      }

      // Asocia la función al evento input de los campos de texto
      const camposDeTexto = document.querySelectorAll('input[type="text"], textarea');
      camposDeTexto.forEach(function (campo) {
          campo.addEventListener("input", function () {
              convertirAMayusculas(campo);
          });
      });
  });
</script>
{% endblock %}

aplicacion/templates/calle_confirm_delete.html
{% extends "base.html" %}

{% block contenido %}
  <div class="card" style="max-width: 600px; margin: 0 auto;">
    <div class="card-header">
      <h2>¿Estás seguro de que deseas eliminar el bloque "{{ object }}"?</h2>
    </div>
    <div class="card-body">
      <form method="post">
        {% csrf_token %}
        <div class="mb-3">
          <p class="lead">Esta acción no se puede deshacer.</p>
        </div>
        <button type="submit" class="btn btn-danger">Eliminar</button>
        <a href="{% url 'calle-list' %}" class="btn btn-secondary ml-2">Cancelar</a>
      </form>
    </div>
  </div>
{% endblock %}



aplicacion/templates/registrar_pagos.html
{% extends "base.html" %}
{% load static %}

{% block contenido %}

<style>
    /* Ajustar el tamaño de fuente para todo el contenedor */
    .container {
        font-size: 20px; /* Puedes ajustar este valor según tu preferencia */
    }

    /* Aumentar el tamaño de fuente para los encabezados */
    h1 {
        font-size: 25px; /* Puedes ajustar este valor según tu preferencia */
    }

    /* Aumentar el tamaño de fuente para los elementos de la lista */
    .list-group-item {
        font-size: 16px; /* Puedes ajustar este valor según tu preferencia */
    }

    /* Estilo para el formulario */
    .formulario-pago {
        font-size: 16px;
        padding: 20px;
    }

    /* Estilo para los botones */
    .btn-registrar-pago {
        margin-top: 10px;
    }

    input[type="text"],
    input[type="date"],
    select,
    textarea {
        width: 100%; /* Ancho completo para todos los campos de entrada y select */
        padding: 10px;
        border: 1px solid #004cff;
        border-radius: 5px;
        margin-bottom: 10px;
    }

    .input-group {
    display: flex; /* Para alinear elementos horizontalmente */
    align-items: center; /* Para alinear elementos verticalmente */
    width: 100%; /* Ajusta el ancho según sea necesario */
    padding: 10px;
    border: 1px solid #004cff;
    border-radius: 5px;
}

/* Estilo específico para el campo de entrada en el spin button */
.input-group input[type="number"] {
    width: 100%; /* Ajusta el ancho del campo de entrada */
    border: none; /* Puedes eliminar el borde si lo prefieres */
    padding: 0;
    margin: 0;
}

/* Estilo específico para los botones del spin button */
.input-group button {
    background: #004cff;
    color: #fff;
    border: none;
    padding: 5px 10px;
    border-radius: 5px;
    cursor: pointer;
}

/* Estilo cuando se pasa el cursor sobre los botones */
.input-group button:hover {
    background: #0030a1; /* Puedes cambiar el color al pasar el cursor si lo deseas */
}

.titulo {
    background: linear-gradient(45deg, #007bff, #00bcd4);
    color: #fff;
    font-size: 40px;
    padding: 10px;
    text-align: center;
    border-radius: 5px;
    margin-bottom: 20px;
    margin-top: 20px; /* Agregamos margen superior para separar el título de los botones */
}

#id_comprobante_pago {
    width: 100%;
    padding: 10px;
    border: 1px solid #004cff;
    border-radius: 5px;
    font-size: 16px;
    color: #007bff;
    background-color: #f7f7f7;
}
    /* Estilo para el contenedor del campo de fecha y hora */
    .fecha-hora-container {
        margin-top: 10px;
    }

    /* Estilo para el campo de fecha y hora */
    input[type="datetime-local"] {
        width: 100%;
        padding: 10px;
        border: 1px solid #004cff;
        border-radius: 5px;
    }

        /* Estilo para el campo de selección 'jefe_de_familia' */
    .jefe-familia-select {
        width: 100%;
        padding: 10px;
        border: 1px solid #004cff;
        border-radius: 5px;
        }

    textarea[name="observaciones"]{
    width: 100%; /* Ajusta el ancho según tus preferencias */
    height: 100px; /* Ajusta la altura según tus preferencias */
    font-size: 14px; /* Ajusta el tamaño del texto según tus preferencias */
    }

    /* Estilo para campos con borde azul */
.border-blue {
    border: 1px solid #004cff; 
    /* Puedes ajustar el color según tus preferencias */
}

input[type="text"],
input[type="date"],
select,
textarea,
input[type="email"],
.form-control {
    width: 100%;
    padding: 10px;
    border: 1px solid #004cff;
    border-radius: 5px;
    font-size: 16px;
    color: #007bff;
    background-color: #f7f7f7;
}

.select2-selection__rendered {
    border: 1px solid #004cff;
    border-radius: 5px;
    padding: 10px;
    font-size: 16px;
    color: #333;
    background-color: #f7f7f7;
}


</style>
{% if form.errors %}
<div class="alert alert-danger" role="alert">
  <strong>Error en el formulario:</strong>
  {% for field, errors in form.errors.items %}
    <p>{{ field }}:
      {% for error in errors %}
        {{ error }}
      {% endfor %}
    </p>
  {% endfor %}
</div>
{% endif %}
<div class="card">
    <div class="card-body">
        <div class="titulo">Registrar Pagos</div>
        <form method="post" enctype="multipart/form-data" id="pagos-form">
            {% csrf_token %}

            <div class="row">
                <!-- Primera columna de campos -->
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Fecha</label>
                        {{ form.fecha}}   
                    </div>             
                    <div class="form-group">
                        <label for="{{ form.jefe_de_familia.id_for_label }}">Jefe de Familia</label>
                        {{ form.jefe_de_familia }}
                    </div>
                    <div style="margin-bottom: 28px;"></div>
                    <div style="margin-bottom: 28px;"></div>
                    <div class="form-group">
                        <label for="{{ form.banco_receptor.id_for_label }}">Banco Receptor</label>
                        {{ form.banco_receptor }}
                    </div>
                    <div class="form-group">
                        <label for="{{ form.banco_emisor.id_for_label }}">Banco Emisor</label>
                        {{ form.banco_emisor }}
                    </div>  
                </div>
                
                <!-- Segunda columna de campos -->
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="{{ form.numero_referencia.id_for_label }}">Número de Referencia</label>
                        <input type="text" name="{{ form.numero_referencia.name }}" id="{{ form.numero_referencia.id }}" minlength="6" maxlength="6" class="form-control">
                        <span id="error-message" style="color: red; display: none;">Solo se permiten 6 números.</span>
                    </div>
                    <div style="margin-bottom: 18px;"></div>
                    <div class="form-group">
                        <label for="{{ form.monto.id_for_label }}">Monto</label>
                        <div class="input-group">
                            {{ form.monto }}
                        </div>
                    </div>
                    <div style="margin-bottom: 8px;"></div>
                    <div class="form-group">
                        <label for="{{ form.comprobante_pago.id_for_label }}">Comprobante de Pago</label>
                        {{ form.comprobante_pago }}
                    </div>
                    <div class="form-group">
                        <label>Observaciones:</label>
                        {{ form.observaciones }}   
                    </div> 
                </div>
                
                
            
            <div class="text-center">
                <button id="guardar-pago-button" class="btn btn-primary btn-registrar-pago">Guardar Pago</button>
                <a href="{% url 'ListaPagos' %}" class="btn btn-danger btn-registrar-pago">Cancelar</a>
            </div>
        </form>
    </div>
</div>


<script>
    // Función para formatear automáticamente el campo de monto
    function formatCurrency() {
        // Obtener el valor actual del campo de monto
        let value = document.getElementById('id_monto').value;

        // Eliminar cualquier caracter no numérico y ceros a la izquierda
        value = value.replace(/^0+/g, '').replace(/[^\d]/g, '');

        // Asegurarse de que haya al menos un dígito
        if (value === '') {
            value = '0';
        }

        // Añadir cero a la izquierda si solo hay un dígito
        if (value.length === 1) {
            value = '0' + value;
        }

        // Formatear el valor como moneda (en este caso, formato de dólares)
        const formattedValue = (parseFloat(value) / 100).toFixed(2);

        // Actualizar el valor del campo
        document.getElementById('id_monto').value = formattedValue;
    }

    // Evento input para el campo de monto
    document.getElementById('id_monto').addEventListener('input', formatCurrency);

    // Evento input para el campo de número de referencia
    document.getElementById('{{ form.numero_referencia.id }}').addEventListener('input', function () {
        // Permitir solo caracteres numéricos
        this.value = this.value.replace(/\D/g, '');
    });

    function realizarPago() {
        // Puedes agregar aquí la lógica para procesar el pago con el monto actual
        alert('Pago realizado por: ' + document.getElementById('id_monto').value);
    }

    const numeroReferenciaInput = document.getElementById("{{ form.numero_referencia.id }}");
    const errorMessage = document.getElementById("error-message");

    numeroReferenciaInput.addEventListener("input", function () {
        if (this.value.length > 6) {
            this.value = this.value.slice(0, 6);
            errorMessage.style.display = "block";
        } else {
            errorMessage.style.display = "none";
        }
    });

</script>




{% endblock %}